networks:
  traefik_public:
    name: traefik_public_network
  backend:
    name: backend_network
    internal: true

services:
  traefik:
    container_name: room-reservation_traefik
    restart: always
    image: traefik:3.6.6
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - ./docker/traefik/dev.traefik.toml:/traefik.toml
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - traefik_public
      - backend
    labels:
      - "traefik.enable=true"

  database:
    container_name: room-reservation_db
    restart: always
    image: postgres:18-alpine
    env_file:
      - ./docker/database/.env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql
    networks:
      - traefik_public
      - backend
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 5s
      timeout: 3s
      retries: 10
      start_period: 30s
    labels:
      - "traefik.enable=false"

  api:
    container_name: room-reservation_api
    restart: always
    build: ./backend
    depends_on:
      database:
        condition: service_healthy
    env_file:
      - backend/.env
    networks:
      - backend
    labels:
      - "traefik.enable=true"
      - "traefik.http.middlewares.api.stripprefix.prefixes=/api/"
      - "traefik.http.routers.api.rule=Host(`room-reservation.localhost`)&&PathPrefix(`/api/`)"
      - "traefik.http.routers.api.middlewares=api"
      - "traefik.http.routers.api.entrypoints=web"
      - "traefik.http.routers.api.service=api"
      - "traefik.http.services.api.loadbalancer.server.port=3000"
      - "traefik.docker.network=backend_network"

volumes:
  postgres_data:
    name: room-reservation-postgres-data
